### ISSUE TITLE
This package is marked as being compatible with Flutter Web, but it isn't; unless I've missed something?

### ISSUE THREAD

**Issue by genjm** [dart-lang/web_socket_channel#119]
Afternoon,

The example code doesn't run in flutter web, you get the following exception:

`Error: Unsupported operation: Platform._version
    at Object.throw_ [as throw] (http://localhost:55950/dart_sdk.js:4461:11)
    at Function._version (http://localhost:55950/dart_sdk.js:54369:17)
    at Function.get version [as version] (http://localhost:55950/dart_sdk.js:54443:27)
    at get _version (http://localhost:55950/dart_sdk.js:54313:27)
    at Function.desc.get [as _version] (http://localhost:55950/dart_sdk.js:4941:15)
    at Function.get version [as version] (http://localhost:55950/dart_sdk.js:54287:26)
    at Object._getHttpVersion (http://localhost:55950/dart_sdk.js:178015:31)
    at new _http._HttpClient.new (http://localhost:55950/dart_sdk.js:173075:28)
    at Function.new (http://localhost:55950/dart_sdk.js:167766:16)
    at get _httpClient (http://localhost:55950/dart_sdk.js:178011:34)
    at Function.desc.get [as _httpClient] (http://localhost:55950/dart_sdk.js:4941:15)
    at Function.connect (http://localhost:55950/dart_sdk.js:177644:35)
    at Function.connect (http://localhost:55950/dart_sdk.js:176359:35)
    at Function.connect (http://localhost:55950/packages/web_socket_channel/io.dart.lib.js:76:94)
    at main (http://localhost:55950/packages/realtime_display/main.dart.lib.js:13:50)
    at main.next (<anonymous>)
    at runBody (http://localhost:55950/dart_sdk.js:36923:34)
    at Object._async [as async] (http://localhost:55950/dart_sdk.js:36951:7)
    at Object.main$ [as main] (http://localhost:55950/packages/realtime_display/main.dart.lib.js:12:18)
    at main$ (http://localhost:55950/web_entrypoint.dart.lib.js:14:12)
    at main$.next (<anonymous>)
    at http://localhost:55950/dart_sdk.js:36903:33
    at _RootZone.runUnary (http://localhost:55950/dart_sdk.js:36757:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55950/dart_sdk.js:31921:29)
    at handleValueCallback (http://localhost:55950/dart_sdk.js:32462:49)
    at Function._propagateToListeners (http://localhost:55950/dart_sdk.js:32494:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55950/dart_sdk.js:32232:27)
    at Object._microtaskLoop (http://localhost:55950/dart_sdk.js:37015:13)
    at _startMicrotaskLoop (http://localhost:55950/dart_sdk.js:37021:13)
    at http://localhost:55950/dart_sdk.js:32708:9Application finished.`

Has the package been tagged incorrectly, or have I missed something that needs to be changed when running in web?

Thanks.

**Comment by thanksmister** [comment]
I am running this package in Flutter web without issues.  I am on Flutter beta channel.  I am running version 1.1.0

**Comment by natebosch** [comment]
You can't import `web_socket_channel/io.dart` on the web. The flutter team chose to allow this statically but it will fail at runtime.

cc @jonahwilliams - is there a tracking issue for disallowing these imports statically?

The solution is to import `package:web_socket_channel/web_socket_channel.dart` instead of `package:web_socket_channel/io.dart`.

**Comment by jonahwilliams** [comment]
My understanding of the situation is that the analyzer does not have the capability to analyze with two SDKs at once, so it cannot know that something is a flutter web app - partially because there isn't really any distinction between a flutter app and a flutter web app.

The closest tracking issue would be https://github.com/flutter/flutter/issues/39998

**Comment by natebosch** [comment]
This isn't the analyzer issue, this is the issue where if you build with `build_runner build` you get a warning that there is an unsupported import to `dart:io`, but if you build with `flutter build` you don't get any indication that there is a problem, but the APIs throw at runtime.

Specifically I mean the usage of `skipPlatformCheck`

https://github.com/natebosch/flutter/blob/6d9b6aec453303a3bc02fb94162c45a014c64c58/packages/_flutter_web_build_script/lib/build_script.dart#L235

**Comment by jonahwilliams** [comment]
We do not use build_runner to build web applications anymore, so that would require the CFE to acknowledge the restriction.

**Comment by natebosch** [comment]
Sounds good. I'll follow up with the web compiler and CFE teams about this.

Do you know if the flutter framework is ready for these to be disallowed or is there more work that needs to be done there before we can enable that check for flutter web?

**Comment by jonahwilliams** [comment]
The framework itself still requires updates, since dart:io and dart:isolate leak out the public API in a few places. You should rope in someone from the framework team and plugin team to figure out how it could be landed.

My gut feeling is that unless we have alternative APIs (package:platform ?) it will be impossible to land today

**Comment by jonahwilliams** [comment]
specifically @goderbauer & @amirh  to start with

**Comment by natebosch** [comment]
Sounds good. We won't make any changes in the short term and make sure there is lots of communication and/or an opt-out for flutter before we disallow those imports.
