### ISSUE TITLE
trying to connect to wrong port

### ISSUE THREAD

**Issue by ash-hashtag** [dart-lang/web_socket_channel#241]
```
  final uri = Uri.parse("ws://192.168.0.167:8080");
  
  debugPrint("connecting... ${uri.host} ${uri.port}");
  
  final socket = WebSocketChannel.connect(uri);
```

the uri is correctly getting parsed
but the socket throws exception after a minute, Connection TimedOut and displays wrong port, I didn't have the issue before.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: WebSocketChannelException: WebSocketChannelException: SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 192.168.0.167, port = 53474
E/flutter (21791): #0      new IOWebSocketChannel._withoutSocket.<anonymous closure>
package:web_socket_channel/io.dart:98
E/flutter (21791): #1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:929:16)
E/flutter (21791): #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
E/flutter (21791): #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter (21791): #4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
E/flutter (21791): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter (21791): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
E/flutter (21791): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (21791): #8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter (21791): #9      _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter (21791): #10     _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
E/flutter (21791): #11     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter (21791): #12     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
E/flutter (21791): #13     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (21791): #14     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter (21791): #15     _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter (21791): #16     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:251:18)
E/flutter (21791): #17     _RootZone.runBinary (dart:async/zone.dart:1658:54)
E/flutter (21791): #18     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (21791): #19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter (21791): #20     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter (21791): #21     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (21791): #22     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter (21791): #23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (21791): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

and the ports are randomly generated? I tried to start the server with the port before it crashed, and it's not a default value but a new port everytime?

**Comment by KingCosmic** [comment]
Having the same issue

**Comment by KingCosmic** [comment]
will say https://github.com/dart-lang/web_socket_channel/issues/216#issuecomment-1339600162 this seems to be a solution though.

**Comment by ash-hashtag** [comment]
> will say [#216 (comment)](https://github.com/dart-lang/web_socket_channel/issues/216#issuecomment-1339600162) this seems to be a solution though.

No, look at the ip I'm using, I'm indeed connecting to the correct local ip address, not localhost, and I don't know why, but it broke currently, I have used the same thing a month ago, and worked fine(both are different apps) that app is still working

**Comment by ash-hashtag** [comment]
It's not a problem of this package, even using websocket from dart:Io results in same error

**Comment by ash-hashtag** [comment]
@KingCosmic  did #216 solved your problem?

**Comment by ash-hashtag** [comment]
It's windows firewall, solved it by disabling it, I don't know why tho it allows http requests from different devices on the same network but websockets don't work? The error could give some accurate info tho, like what does it mean "trying to connect different port and failing"? How could it let us debug where the issue is, I don't know the problem is in windows side or dart side for showing the error like that. but If the error just showed failed to connect to the "correct" port, We would've looked for the correct solution sooner.
